### ISSUE TITLE
Every time i try to clicl login to craxrat i grt no wifi and the loader dont load

### ISSUE THREAD

**Issue by Ghostofthewest03** [Cryakl/Ultimate-RAT-Collection#12]
How to fix

**Comment by Cryakl** [comment]
Hello, if this is Craxs Rat v5.1 you're attempting to use here are some instructions:

1. Run the "Loader.exe" in the "Loader" directory and keep it running.
2. Launch the CraxsRat executable, wait a while for it to launch, it takes some time.
3. Input any e-mail and key and the loader will then redirect the traffic and accept the login.
4. Go to 'Proxy Settings' in Windows after you've got in and turn off the proxy.
5. You should be able to use CraxsRat without problems after this.

![image](https://github.com/user-attachments/assets/2bff9439-f696-47da-885b-aa55fe3b82a1)

Photo here showing what to turn off.

**Comment by Cryakl** [comment]
Closing due to old issue/no response.
