### ISSUE TITLE
Malwarebytes detected Neshta.Virus.FileInfector.DDS in NJRat, is it safe?

### ISSUE THREAD

**Issue by powerty989** [Cryakl/Ultimate-RAT-Collection#13]

**Comment by Cryakl** [comment]
Can you tell me which one you downloaded? I've verified every edition of njRat i've collected is free from fileinfectors.
I think your system is infected by the Neshta fileinfector, can you check if the file 'C:\Windows\svchost.com' exists?

If so, it's currently every .exe file you download and use, which to clear up you'd probably want to factory reset your PC, you can back up everything that isn't an .exe file.

**Comment by powerty989** [comment]
> Can you tell me which one you downloaded? I've verified every edition of njRat i've collected is free from fileinfectors. I think your system is infected by the Neshta fileinfector, can you check if the file 'C:\Windows\svchost.com' exists?
> 
> If so, it's currently infecting every .exe file you download and use, which to clear up you'd probably want to factory reset your PC, you can back up everything that isn't an .exe file.
0.7 Green edition

**Comment by Cryakl** [comment]
> > Can you tell me which one you downloaded? I've verified every edition of njRat i've collected is free from fileinfectors. I think your system is infected by the Neshta fileinfector, can you check if the file 'C:\Windows\svchost.com' exists?
> > If so, it's currently infecting every .exe file you download and use, which to clear up you'd probably want to factory reset your PC, you can back up everything that isn't an .exe file.
> > 0.7 Green edition

0.7 Green Edition is clean, I think your system was infected by Neshta some point else from another EXE on the internet.

**Comment by Cryakl** [comment]
Closing due to old issue/no response.
