### ISSUE TITLE
I broke 888 rat 

### ISSUE THREAD

**Issue by TG-NOBODY** [Cryakl/Ultimate-RAT-Collection#14]
It worked but now it just shows this error
https://imgur.com/a/2kwd3mG

**Comment by Cryakl** [comment]
You'll probably have to go into the registry, 888 RAT stores configuration/license data in the registry.
It's common when you've used an older version of it, then tried a new version after.

**Comment by TG-NOBODY** [comment]
Ah ok thanks can u please link a tutorial or something i have no clue how to do that

**Comment by TG-NOBODY** [comment]
fixed it thanks

**Comment by Cryakl** [comment]
Thankfully you've fixed it, sorry, I've been offline for a few days and couldn't help out.
