### ISSUE TITLE
Port forwarding not working in XWorm even after allowing port forwarding in router options

### ISSUE THREAD

**Issue by powerty989** [Cryakl/Ultimate-RAT-Collection#15]
Help

**Comment by Ghazouai** [comment]
the same problem happened to me, but i found a way to port forward without using ur router:
1. go to portmap.io
2. watch some yt videos bout this website they will show u how to do it cuz im busy typing all the steps
3. and thats it
hope that helps

**Comment by Cryakl** [comment]
Closing due to old issue/no response.

**Comment by ImTheOneWhoWatches** [comment]
Could be a double nat issue, go check it.
