### ISSUE TITLE
More Detailed Explanation 

### ISSUE THREAD

**Issue by ImTheOneWhoWatches** [Cryakl/Ultimate-RAT-Collection#20]
For bitrat, I attempt to build it with my ip. It forces me to do the tor service junk. Can you explain the little tutorial better, as well as adding the "config" for the tutorial too?

**Comment by Cryakl** [comment]
This should explain how to create a stub without Tor Service, and instead, a normal DNS/IP.

https://github.com/user-attachments/assets/567702d4-8a3a-4aee-bfd7-ab0e55b77aba
