### ISSUE TITLE
XWorm download

### ISSUE THREAD

**Issue by Nkaslqi** [Cryakl/Ultimate-RAT-Collection#35]
The archive 002 is downloaded with .002 extension, do i need to download the entire repository?

**Comment by Cryakl** [comment]
Yeah, you would need to download the entire thing for it to extract properly. 

If you have Telegram I can send you these files properly without you having to download the entire repo.

**Comment by Nkaslqi** [comment]
> Yeah, you would need to download the entire thing for it to extract properly.
> 
> If you have Telegram I can send you these files properly without you having to download the entire repo.

oh that would be amazing, https://t.me/AnonKernel
