### ISSUE TITLE
RAT RAT RAT RAT

### ISSUE THREAD

**Issue by 8msv** [Cryakl/Ultimate-RAT-Collection#8]
THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS  THE BUILDERS ARE RATS
![Screenshot 2024-08-02 171200](https://github.com/user-attachments/assets/c17c9fa0-0534-4c37-beb3-cc71d67e8761)

**Comment by Cryakl** [comment]
I'm not sure if you realize, but this is static analysis from Triage.

It's looking at the plugins here such as "Recovery.dll" or "Stealer.dll".
XWorm is infamous for being a hybrid based off of other RAT source codes.
Hence, the StormKitty detection which is also partially ripped off AsyncRat.

As for the AgentTesla detection, this is generic and a false positive.
Happens even when you analyze SpyNote, Anarchy Panel, EagleSpy, etc. on Triage.

The XWorm V5.6 executable is relatively unobfuscated as well as the plugins.
So feel free to decompile it with dnSpy or JustDecompile.
