### ISSUE TITLE
Any playit.gg alternatives?

### ISSUE THREAD

**Issue by powerty989** [Cryakl/Ultimate-RAT-Collection#9]
I am looking for playit.gg alternative since it is not working on rats.

**Comment by titu3e** [comment]
> I am looking for playit.gg alternative since it is not working on rats.

could u explain more what does it do exactly? do u want to access devices out of ur network?

**Comment by powerty989** [comment]
> > I am looking for playit.gg alternative since it is not working on rats.
> 
> could u explain more what does it do exactly? do u want to access devices out of ur network?

when i open built rat exe file, my user not appearing in list

**Comment by titu3e** [comment]
> > > I am looking for playit.gg alternative since it is not working on rats.
> > 
> > 
> > could u explain more what does it do exactly? do u want to access devices out of ur network?
> 
> when i open built rat exe file, my user not appearing in list

use ngrok and open a tcp port using `ngrok tcp port ` port should be the one that the rat exe file has server running on probably 7771 or 7777 so the command looks like `ngrok tcp 7777/7771 ` then this will give u a tcp link like tcp://xyz.ngrok.in:port or somthing  use that to build the exe or apk

**Comment by powerty989** [comment]
> > > > I am looking for playit.gg alternative since it is not working on rats.
> > > 
> > > 
> > > could u explain more what does it do exactly? do u want to access devices out of ur network?
> > 
> > 
> > when i open built rat exe file, my user not appearing in list
> 
> use ngrok and open a tcp port using `ngrok tcp port ` port should be the one that the rat exe file has server running on probably 7771 or 7777 so the command looks like `ngrok tcp 7777/7771 ` then this will give u a tcp link like tcp://xyz.ngrok.in:port or somthing use that to build the exe or apk

Isn't ngrok needs cc?

**Comment by titu3e** [comment]
> > > > > I am looking for playit.gg alternative since it is not working on rats.
> > > > 
> > > > 
> > > > could u explain more what does it do exactly? do u want to access devices out of ur network?
> > > 
> > > 
> > > when i open built rat exe file, my user not appearing in list
> > 
> > 
> > use ngrok and open a tcp port using `ngrok tcp port ` port should be the one that the rat exe file has server running on probably 7771 or 7777 so the command looks like `ngrok tcp 7777/7771 ` then this will give u a tcp link like tcp://xyz.ngrok.in:port or somthing use that to build the exe or apk
> 
> Isn't ngrok needs cc?

no it doesnt

**Comment by powerty989** [comment]
> > > > > > I am looking for playit.gg alternative since it is not working on rats.
> > > > > 
> > > > > 
> > > > > could u explain more what does it do exactly? do u want to access devices out of ur network?
> > > > 
> > > > 
> > > > when i open built rat exe file, my user not appearing in list
> > > 
> > > 
> > > use ngrok and open a tcp port using `ngrok tcp port ` port should be the one that the rat exe file has server running on probably 7771 or 7777 so the command looks like `ngrok tcp 7777/7771 ` then this will give u a tcp link like tcp://xyz.ngrok.in:port or somthing use that to build the exe or apk
> > 
> > 
> > Isn't ngrok needs cc?
> 
> no it doesnt

for me it says error 8013 https://ngrok.com/docs/errors/err_ngrok_8013/

**Comment by Cryakl** [comment]
> > > > > > > I am looking for playit.gg alternative since it is not working on rats.
> > > > > > 
> > > > > > 
> > > > > > could u explain more what does it do exactly? do u want to access devices out of ur network?
> > > > > 
> > > > > 
> > > > > when i open built rat exe file, my user not appearing in list
> > > > 
> > > > 
> > > > use ngrok and open a tcp port using `ngrok tcp port ` port should be the one that the rat exe file has server running on probably 7771 or 7777 so the command looks like `ngrok tcp 7777/7771 ` then this will give u a tcp link like tcp://xyz.ngrok.in:port or somthing use that to build the exe or apk
> > > 
> > > 
> > > Isn't ngrok needs cc?
> > 
> > 
> > no it doesnt
> 
> for me it says error 8013 https://ngrok.com/docs/errors/err_ngrok_8013/

This was introduced recently as ngrok has been abused too much in the past for RAT C2s.
New accounts are now required to do a KYC check, IE: Credit Card here.

**Comment by powerty989** [comment]
can it be problems with ip or because i am building on vm?

**Comment by titu3e** [comment]
> > > > > > > > I am looking for playit.gg alternative since it is not working on rats.
> > > > > > > 
> > > > > > > 
> > > > > > > could u explain more what does it do exactly? do u want to access devices out of ur network?
> > > > > > 
> > > > > > 
> > > > > > when i open built rat exe file, my user not appearing in list
> > > > > 
> > > > > 
> > > > > use ngrok and open a tcp port using `ngrok tcp port ` port should be the one that the rat exe file has server running on probably 7771 or 7777 so the command looks like `ngrok tcp 7777/7771 ` then this will give u a tcp link like tcp://xyz.ngrok.in:port or somthing use that to build the exe or apk
> > > > 
> > > > 
> > > > Isn't ngrok needs cc?
> > > 
> > > 
> > > no it doesnt
> > 
> > 
> > for me it says error 8013 [ngrok.com/docs/errors/err_ngrok_8013](https://ngrok.com/docs/errors/err_ngrok_8013/)
> 
> This was introduced recently as ngrok has been abused too much in the past for RAT C2s. New accounts are now required to do a KYC check, IE: Credit Card here.

ohh i didnt know that cuz i have an old accnt

**Comment by titu3e** [comment]
> can it be problems with ip or because i am building on vm?

u need to port forward it so that the ip is accessible remotely if u are using a router then this can be done ig but i aint sure

**Comment by powerty989** [comment]
> > can it be problems with ip or because i am building on vm?
> 
> u need to port forward it so that the ip is accessible remotely if u are using a router then this can be done ig but i aint sure

what if vm where i use builders has different default gatewat than my pc

**Comment by Cryakl** [comment]
> > > can it be problems with ip or because i am building on vm?
> > 
> > 
> > u need to port forward it so that the ip is accessible remotely if u are using a router then this can be done ig but i aint sure
> 
> what if vm where i use builders has different default gatewat than my pc

You can change the network settings, plenty of stuff on google explaining Bridged, NAT, Host-only, etc.
I'll close this issue for now as it's been a week.
